### ISSUE TITLE
Playing AVI File Error

### ISSUE THREAD

**Issue by linuxstv** [Taapat/enigma2-openpli-fulan#1]
Hi bro,

I've tried your new image based on OpenPLi 5. This image is good, but this is may be a bug need to be resolved. When I play AVI media file, I got only sound but no video and the serial log shows this:

[container_ffmpeg.c:FFMPEGThread] 
[container_ffmpeg.c:FFMPEGThread] Running!
[output/linuxdvb.c:LinuxDvbPts] VIDEO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] AUDIO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] VIDEO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] AUDIO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] VIDEO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] AUDIO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] VIDEO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] AUDIO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] VIDEO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] AUDIO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] VIDEO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] AUDIO_GET_PTS: 22 (Invalid argument)
resolved to PLAY
[playback.c:PlaybackContinue] continue not possible
new service started! trying to download cuts!
RemovePopup, id = ZapError
[eServiceMP3::start] start /media/net/zparkPEDODE/TOURO/Movies/Cartoon/Transformers/Transformers.Headmasters.1987.DVDRip.XviD.MP3/Transformers Headmasters - 01 - Four Warriors From Outer Space.avi
[output/linuxdvb.c:LinuxDvbPts] VIDEO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] VIDEO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] VIDEO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] VIDEO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] VIDEO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] VIDEO_GET_PTS: 22 (Invalid argument)
[output/linuxdvb.c:LinuxDvbPts] VIDEO_GET_PTS: 22 (Invalid argument)

I hope it's resolved on the next release.

**Comment by Taapat** [comment]
Hi,
I suppose that such errors are not with all avi files.
Maybe you can cut on a small piece from this file, and share for test?

**Comment by linuxstv** [comment]
You're right bro, it only happens on my certain avi files. Here's the first 25 seconds clip of the file:

[Test-Headmaster.avi.zip](https://github.com/Taapat/enigma2-openpli-fulan/files/94845/Test-Headmaster.avi.zip)
