### ISSUE TITLE
No more serial debug by default?

### ISSUE THREAD

**Issue by linuxstv** [Taapat/enigma2-openpli-fulan#10]
I'm so sorry for this. Is it intended to disable serial debug by default?

I only get this kind of log on my terminal via RS232:

> PYTHONPATH: /usr/lib/enigma2/python
DVB_API_VERSION 5 DVB_API_VERSION_MINOR 1
ENIGMA_DEBUG_LVL=3
[MAIN] executing main
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux

Thank you.

**Comment by Taapat** [comment]
A very long time ago openpli disabled enigma log.
This improves performance.
If it necessary log you can change the debug level in enigma2.sh:
`LD_PRELOAD=$LIBS  ENIGMA_DEBUG_LVL=4 /usr/bin/enigma2`

Or in Tools/RedirectOutput.py change to lvlDebug = 4

**Comment by linuxstv** [comment]
Thank you for the hints. I still use serial log because it's easy to find the error when something goes wrong (especially on green screen). No need to log on telnet console and re-init the Enigma.

**Comment by Taapat** [comment]
I also use the log in the serial, but only when I need it.
