### ISSUE TITLE
Request for update to OpenPli 7 (Spark Reloaded)

### ISSUE THREAD

**Issue by sevospl** [Taapat/enigma2-openpli-fulan#12]
Hi!

It's related to http://taapat.ho.ua/, where I can get an image for Spark Reloaded - it worked well but there's a huge lack of features that are already available in 7.

Would you mind updating this to the newest version? I'd appreciate that :)

**Comment by Taapat** [comment]
Hi!

Sorry but due to lack of time I've stopped fulan updates for a long time.
