### ISSUE TITLE
Some channels are laggy

### ISSUE THREAD

**Issue by linuxstv** [Taapat/enigma2-openpli-fulan#2]
Hi bro,

I wanna report about some channels are not normal. Signal strength and quality is good, but channels are laggy (only certain channels actually, for example Kompastv and inews on Palapa D). Oh, one more, C Music on Asiasat 5 makes the box unresponsive and needs reboot.

I attach files on this issue.
[some channels are laggy-video-2016-02-05-05-29-08.mp4.zip](https://github.com/Taapat/enigma2-openpli-fulan/files/118365/some.channels.are.laggy-video-2016-02-05-05-29-08.mp4.zip)

![1_0_1_1_1000_2000_46b8fd3_0_0_0](https://cloud.githubusercontent.com/assets/15664372/12832356/05670f28-cbcc-11e5-84b3-b264d8c9cb0c.jpg)

**Comment by Fauzinani** [comment]
Up

**Comment by linuxstv** [comment]
By the way, this problem can be solved if only player2 source code is updated to the latest one.

**Comment by Taapat** [comment]
And which you call about the latest one?
If you are talking about Duckbox-Developers, then try mkv.
You will have a problems with many.

Sorry, but I prefer working mkv instead of some HD channels that I do not watch.

**Comment by linuxstv** [comment]
![mkv movie](https://cloud.githubusercontent.com/assets/15664372/18393644/6d08aa64-76e0-11e6-9c60-bdd01eca1bd8.jpg)

![mkv movie cosmos](https://cloud.githubusercontent.com/assets/15664372/18393669/7a584b3e-76e0-11e6-8158-a70b3a9c5202.jpg)

Haven't found any problem so far of the mkv files played on the Media Player via Samba.

By the way, thank for the explanation and for the great image for Spark.
