### ISSUE TITLE
Released 20160601 BitrateCalc Error

### ISSUE THREAD

**Issue by linuxstv** [Taapat/enigma2-openpli-fulan#6]
Hi guys,

I tried the latest build i.e "openpli-enigma2-5-spark_20160601.zip". The error shows up when Bitrate2.py calls to "bitratecalc.so":

> try:
>     from bitratecalc import eBitrateCalculator
> except:
>     pass

Debug on terminal prints this crashlog:

> new service started! trying to download cuts!
> download failed, no cuesheet interface
> RemovePopup, id = ZapError
> [ePopen] command: route -n | grep  eth0
> Traceback (most recent call last):
>   File "/usr/lib/enigma2/python/Components/Converter/Bitrate2.py", line 68, in initBitrateCalc
>     self.videoBitrate = eBitrateCalculator(vpid, dvbnamespace, tsid, onid, 1000, 1024*1024) # pid, dvbnamespace, tsid, onid, refresh intervall, buffer size
> NameError: global name 'eBitrateCalculator' is not defined
> Killed

![bitrate2 py cant load bitratecalc so](https://cloud.githubusercontent.com/assets/15664372/16537559/f75d1052-402f-11e6-8532-250beccaafde.png)

Previous release is normal with this bitratecalc.so. Thanks and wish to find a solution on this problem.

Regards,
Budiarno

**Comment by Taapat** [comment]
Hi,
please try this bitratecalc: http://taapat.ho.ua/Download/bitratecalc-enigma2-5-spark_20160601.zip

**Comment by linuxstv** [comment]
Thank you bro, problem solved.
