### ISSUE TITLE
Power Button Config is Missing

### ISSUE THREAD

**Issue by linuxstv** [Taapat/enigma2-openpli-fulan#7]
Hi,
Did you guys intentionally remove these lines on 'setup.xml' file?

> ```
>   <item level="1" text="Action on long powerbutton press" description="Configure the function of a long press on the power button.">config.usage.on_long_powerpress</item>
>     <item level="1" text="Action on short powerbutton press" description="Configure the function of a short press on the power button.">config.usage.on_short_powerpress</item>
> ```

If it did, where should I go about making this config working again as the previous setup?

Thank you.

**Comment by Taapat** [comment]
https://github.com/Taapat/enigma2-openpli-fulan/commit/939f4d3ce27cdbe6340d18f0222412443a243ae5
